server:
  port: 8087
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/passionchenjianye/xunyijia-config
          searchPaths: config  # 配置中心的配置其实是在git仓库里，通过设置git uri可以获取到相应的配置
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8081/eureka/